server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker #Rama de git
          uri: https://github.com/MaximilianoLutz/invitacion
          search-paths: /config-data
  application:
    name: microservicio-config